### ISSUE TITLE
create species-specific R script for multi-species project

### ISSUE THREAD

**Issue by hxin** [sidbdri/cookiecutter-de_analysis_skeleton#104]
Currently, cookiecutter will generate in total one pair of (meta_data.R, diff_expr.R), we can possibly try to creat, for each species,  one pair of (meta_data.R, diff_expr.R).

**Comment by lweasel** [comment]
Now that we are creating per-species R scripts, is it possible to remove the *non*-per-species scripts? i.e. if I create a single-species rat project, I now get "diff_expr.R" and "diff_expr_rat.R", and "meta_data.R" and "meta_data_rat.R". I wonder if we could remove "diff_expr.R" and "meta_data.R"? (and also make run_analysis.sh execute the species-specific scripts?).

**Comment by lweasel** [comment]
p.s. What's the "species" column in COMPARISON_TABLE used for? Do we need this?

**Comment by hxin** [comment]
> p.s. What's the "species" column in COMPARISON_TABLE used for? Do we need this?

I can't remember why I add that column?! I don't think it is used anywhere! 
I will remove it for now...

**Comment by katieemelianova** [comment]
I've used this in a docker run and am finding an issue of overwriting. When I create the cookiecutter project, it creates e.g. meta_data.R and meta_data_mouse.R. 

In the initial_setup.sh script, there is a line:

<pre><code>sed 's/unknown_species/mouse/' ./meta_data.R > meta_data_mouse.R
</code></pre>
which takes the code in meta_data.R, replaces unknowns with known species names, and writes over meta_data_mouse.R.

I filled out the meta_data_mouse.R file only, and committed it all.

This led to:

- Docker checks out project
- Runs initial_setup.sh script
- Overwrites the filled in meta_data_mouse.R script with the unfilled meta_data.R script

I think this should be changed so that there is a clear set of files to fill out, and there is no overwriting.

**Comment by hxin** [comment]
Code that only required to run ONCE right after cookiecutter, is refactored into a _project_setup.sh_ script. This file will be run ONCE and it will delete itself afterwards.
