### ISSUE TITLE
Retain overall_filtering_summary.txt in Sargasso projects

### ISSUE THREAD

**Issue by lweasel** [sidbdri/cookiecutter-de_analysis_skeleton#112]
In Sargasso projects, it would be good to start including this file in the sets of results that we distribute via Dropbox (because, as I have just found, people sometime want to know the numbers several years later...and keeping the file would save having to re-run the project). To help us to remember to do this, would it be possible to copy this file to the same place as wherever the sessionInfo.txt and multiqc_report.html files end up at the end of a Docker run?

(This might actually be an issue for the Docker repository).

**Comment by hxin** [comment]
The sessionInfo.txt and the multiqc_report.html are in the project root folder, so should I just copy the overall_filtering_summary.txt file to the project root folder? 

If so, this probably needs to be done in cookiecutter rather than docker,  for example at [here](https://github.com/sidbdri/cookiecutter-de_analysis_skeleton/blob/6b05e243f86cdf1a4a97b6965298527397ae5b37/%7B%7Bcookiecutter.project_name%7D%7D/Snakefile.multispecies_analysis#L28) with something like this:
`mv {params.main_dir}/results/sargasso/filtered_reads/overall_filtering_summary.txt {params.main_dir}`

I am new to snakemake so could you check if this is where it should go to? or is there a better place this should be? @katieemelianova @lweasel

**Comment by lweasel** [comment]
I think sessionInfo.txt and multiqc_report.html are moved from the project root folder to the top level of the results folder at the end of a Docker run? (I guess that with sessionInfo.txt that *has* to be done by Docker, because sessionInfo.txt isn't anything to do with the analysis scripts).

I think we should copy overall_filtering_summary.txt to the top level of the results folder too. In this case, like you say, it can be done with cookiecutter. Katie can you possibly advise where a good place to put this in the snakemake code is?

**Comment by hxin** [comment]
I will change the docker part so it will copy the file to the result folder. 
This can also be done in cookie-cutter if needed I will add the above code to run_analysis.sh.
fixed in docker repo for now at [here](https://github.com/sidbdri/Docker/issues/28)

**Comment by hxin** [comment]
Closing for now as fixed in the Docker repo.
