### ISSUE TITLE
Distinguish samples better in "cell type" graphs

### ISSUE THREAD

**Issue by lweasel** [sidbdri/cookiecutter-de_analysis_skeleton#131]
It would be great if it were easier to read these graphs in the case that there are lots of samples - e.g. we might colour them by combinations of features (e.g. PCA_FEATURES or HEAT_MAP_FEATURES ?).

**Comment by hxin** [comment]
Just went through the code and it is really messy...I think this function needs a big refactoring. I will hold it for now and come back later.

**Comment by lweasel** [comment]
Hi @hxin - just trying to balance out the bits of work that need doing over the next week or two...would you mind if (with your help of course) @katieemelianova took a look at this enhancement?

**Comment by lweasel** [comment]
@katieemelianova if you want to have a look at this? Then feel free to ask any questions of @hxin or me :-)

**Comment by hxin** [comment]
The code is a bit messy since we had that code made for a particular project where we have potential sample mislabelling,  but essentially what it does is, it plots the fpkm of those 'marker genes' and have a simple logic to guess if the sample contains a particular cell-type base on the marker gene expression.  

please feel free if you want to re-implement the code or refactor the code, whichever is easier. let me know if any questions.

**Comment by katieemelianova** [comment]
Fixed in 5e52bddb9fea4bcee018910816cd066b34eaecea and previous commit
