### ISSUE TITLE
Bits of multiqc output missing on snakemakeify branch

### ISSUE THREAD

**Issue by lweasel** [sidbdri/cookiecutter-de_analysis_skeleton#134]
There appear to be two bits missing:

- STAR QC: I'm not sure why this isn't there, I but wonder if somehow the way that multiqc is executed from snakemake means our "multiqc_config.yaml" file isn't being picked up? That file defines which files to look in for STAR QC data (i.e. the "*.log.out" files in the "mapped_reads" directory).

- featureCounts QC: for this, we need to keep the *.summary files that are produced by featureCounts. These currently appear to be deleted on this branch.

**Comment by katieemelianova** [comment]
The featurecounts summary should be fine, I checked on the dev branch (where snakemake is now) and the .counts.summary seems to not be deleted anymore and my test run project appears to have featureCounts included in the multiQC report. This may have been fixed along the way, though if I've misunderstood anywhere please let me know, otherwise I'll assume it's already been fixed!

**Comment by katieemelianova** [comment]
fixed in 117284d340bc56576df4026912a0e124ae997484
