### ISSUE TITLE
linked wrongly created in the data folder

### ISSUE THREAD

**Issue by hxin** [sidbdri/cookiecutter-de_analysis_skeleton#172]
https://github.com/sidbdri/cookiecutter-de_analysis_skeleton/blob/0fec9662aadaf1acff205e07e0b164ee748c2f59/%7B%7Bcookiecutter.project_name%7D%7D/initial_setup.sh#L39

This seems to create a link in both the project data folder and in the original fastq folder, when executed twice?

**Comment by lweasel** [comment]
It looks like `ln` behaves in a different way if `${RNASEQ_DIR}/$sample` already exists. 

```
SYNOPSIS
       ln [OPTION]... [-T] TARGET LINK_NAME   (1st form)
       ln [OPTION]... TARGET                  (2nd form)
       ln [OPTION]... TARGET... DIRECTORY     (3rd form)
       ln [OPTION]... -t DIRECTORY TARGET...  (4th form)
```

i.e. the first time that we `run initial_setup.sh` it is executing the 1st form, but if we run it again it is executing the 3rd form, which creates a link to `{{cookiecutter.rnaseq_samples_dir}}/$sample` within `${RNASEQ_DIR}/$sample`. Since the latter is pointing to `{{cookiecutter.rnaseq_samples_dir}}/$sample`, this means we create a link to that directory within itself!

Can we add a check, and only execute `ln` if `${RNASEQ_DIR}/$sample` doesn't already exist?
