### ISSUE TITLE
Unexpected re-run of parts of copied project

### ISSUE THREAD

**Issue by lweasel** [sidbdri/cookiecutter-de_analysis_skeleton#176]
I used the new script that copies data from an old set of project results to a new Docker container, so that I could just re-run the R parts of the analysis. However, when I ran `run_analysis.sh`, the script seemed to re-run featureCounts and picard?

**Comment by hxin** [comment]
This is due to the required files for these rules are not copied to the new project. 

Picard required some of the files in the data folder, which is not copied, rather, they are generated by the new run, thus 'newer' than the copied files.
The strand.txt file is also not copied, and it is part of the output from the featureCount process. 

One solution might be to have these files also listed in the copy parameter, but this might involve copying files from the 'data' folder. 

I think we discussed before why we put Picard in the data folder rather than the results folder, but I cannot remember the details....

**Comment by hxin** [comment]
All the required file to avoid a re-run are these for bulk rna-seq project:
```

bash ./start_project_in_container.sh --project-name app_microglia_mdaniels --results-name test_reuse_script_from_owen --project-github-commit-hash test_reuse_script --sidb-base-exec-image sidb_executable:1.5.4 \
    --copy \
    --base-dir "/srv/data/results/app_microglia_mdaniels/add_KO_sex_comparison-f53f5c839ae683b76dffbf75c623326c0a287ee0/20211130" \
    --dir "data/picard,./data/" \
    --dir "data/human_ensembl_104,./data/" \
    --dir "data/mouse_ensembl_104,./data/" \
    --dir "strand.txt,./" \
    --dir "results,./" \
    --dir "results/multiqc_report.html,./"
```

**Comment by hxin** [comment]
For now, we need to copy all the required files to avoid the rerun, even tho some of the required files are not in the results directory. 

some of the fixes can be found https://github.com/sidbdri/Docker_utility/issues/9
