### ISSUE TITLE
Add check for illegal characters in COMPARISON_TABLE

### ISSUE THREAD

**Issue by lweasel** [sidbdri/cookiecutter-de_analysis_skeleton#199]
Specifically, the comparison names can't contain minus characters - they actually get interpreted as a minus in the function `plot_pvalue_distribution()`. I guess plus characters would probably do the same, though they're less likely to be used. 

I think we could add a sanity check so that these illegal characters are flagged up? Because it's a rather non-obvious problem...

**Comment by hxin** [comment]
The error was caused by the __filter___ function which was deprecated (see [here](https://dplyr.tidyverse.org/reference/se-deprecated.html)). I have modified the code to use filter_at instead. I also added a check for +/- symbol in the comparison as these are likely to cause issues somewhere else. 

We can review the current code and see if we want to replace the xxx_ function once and for all.
